Java06. ДЗ 02, Ялышева Наталья
rbbelka/java-assignments-2 pull request #1
Opened 2016-09-27 21:04 UTC by rbbelka

2016-10-02 14:54 UTC, jzuken requested changes

2016-10-02 14:54 UTC, jzuken commented on pom.xml
> +    <build>
раз эта штука съедает по одной команде за раз, хорошо бы добавить сюда какой-нибудь плагин для сборки jar'а.

2016-10-02 14:54 UTC, jzuken commented on src/main/java/vcs/Main.java
> +        System.out.println("Incorrect input");
хорошо бы ещё писать, чем он некорректный. хотя бы хелп ко актуальным командам и их синтаксису выводить

2016-10-02 14:54 UTC, jzuken commented on src/main/java/vcs/util/VcsException.java
> +public class VcsException extends Exception {
в названии исключений обычно кодируется информация о проблеме, которой они соответствуют. по этому имени мало что понять можно, к сожалению

2016-10-02 14:54 UTC, jzuken commented on src/main/java/vcs/util/Serializer.java
> +                throw new IOException("File cannot be created");
не надо самостоятельно бросать системные исключения, лучше свои сделать, более информативные

2016-10-02 14:55 UTC, jzuken commented
по архитектуре более-менее норм, туда подальше ещё посмотрим, куда какую функциональность перенести

2016-10-02 14:55 UTC, jzuken commented
про джавадок и тесты не забывайте тоже

2016-10-23 11:39 UTC, jzuken commented
Наталья, не забывайте, пожалуйста, после внесения исправлений делать новый сабмит на hwproj, а то я в спаме уведомлений от гитхаба могу потерять ваши новые коммиты

2017-02-15 08:02 UTC, jzuken requested changes

2017-02-15 08:02 UTC, jzuken commented on pom.xml
> +            <systemPath>${project.basedir}/src/main/resources/commons-codec-1.9.jar</systemPath>
такого файла там не лежит. почему бы его мавеном не выкачивать?
в текущем виде не собирается

2017-02-15 08:02 UTC, jzuken commented on src/main/java/vcs/Main.java
> +        System.out.println("Incorrect input");
ну хотя бы правильный формат аргументов напечатайте, а то поди догадайся, что нужно ввести

2017-02-15 08:02 UTC, jzuken commented on src/main/java/vcs/repo/Repository.java
> +    public void checkoutBranch(String name) throws VcsException, IOException {
лучше явно прописывать, какие типы исключений отсюда могут кидаться. это же часть документации к коду по сути

2017-02-15 10:28 UTC, rbbelka commented on pom.xml
> +            <systemPath>${project.basedir}/src/main/resources/commons-codec-1.9.jar</systemPath>
исправила

2017-02-15 10:36 UTC, rbbelka commented on src/main/java/vcs/repo/Repository.java
> +    public void checkoutBranch(String name) throws VcsException, IOException {
исправила, в командах бросаю VcsException, но всё, что они сами бросают прописано в javadoc'е

2017-02-15 10:45 UTC, rbbelka commented on src/main/java/vcs/Main.java
> +        System.out.println("Incorrect input");
Сделано. Это сообщение выводится когда нет аргументов или первый аргумент - не команда, поэтому тут вывожу то, что надо ввести команду и какие они бывают (с опциями), а если с аргументами команд будет что-то не так, то уже команда выкинет исключение, которое выведет необходимую информацию.

2017-02-16 09:04 UTC, jzuken commented on src/main/java/vcs/repo/Repository.java
> +    public void checkoutBranch(String name) throws VcsException, IOException {
ну лучше всё равно явно прописывать только те исключения, что вы кидаете. во-первых, IDE подскажет при использовании этого метода, какие конкретно исключения ловить, а во-вторых, не позволит вам безнаказанно бросить из этого метода что-то ещё, производное от VcsException, не задекларировав это явным образом

2017-02-16 09:09 UTC, jzuken commented
добавил файл, закоммитил, изменил его, потом сказал на него reset и статус говорит, что он Untracked

2017-02-16 09:09 UTC, jzuken commented
коммит, кстати, проходит, даже если никаких изменений не было вообще

2017-02-16 09:21 UTC, rbbelka commented
@jzuken осознала, что неверно понимала, что должен делать reset. Думала, сбрасывает - это выкидывает из репозитория, то есть и из tracked. Исправлю.

2017-02-16 09:23 UTC, jzuken commented
тесты, которые у вас тут есть, это интеграционные тесты, они проверяют работу всей системы в целом. хочется модульных тестов хотя бы для пары классов, которые проверяют только эти отдельные классы в отрыве от остальных. для этого бывают полезны мок-объекты, про которые мы говорили на занятиях

2017-02-17 00:03 UTC, rbbelka commented
Исправила reset и несодержательные коммиты.

2017-02-17 05:41 UTC, jzuken commented
testLog(vcs.LogTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<3>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at vcs.LogTest.testLog(LogTest.java:45)

2017-02-17 05:43 UTC, jzuken commented
✗ java -jar ../vcs.jar branch qwe
Branch qwe created
➜  me@faraway ~/git/au/yalysheva/target/1 git:(vcs) ✗ java -jar ../vcs.jar checkout qwe
Checked out branch qwe
➜  me@faraway ~/git/au/yalysheva/target/1 git:(vcs) ✗ java -jar ../vcs.jar log
Current branch: master
1: asdsad

а чего лог говорит, что оно в мастере осталось?

2017-02-17 08:15 UTC, rbbelka commented
Бранч, кстати, правду говорит, а лог основывался на том, куда сделан последний коммит в истории, исправляю

2017-02-20 22:12 UTC, merged