Java06. ДЗ 04, Ялышева Наталья
rbbelka/java-assignments-2 pull request #2
Opened 2016-10-18 19:05 UTC by rbbelka

2016-11-02 20:05 UTC, jzuken requested changes

2016-11-02 20:05 UTC, jzuken commented on src/main/java/ftp/ClientMain.java
> +                    case "list":
давайте лучше увековечим протокол в константах, мало ли кто опечатается где

2016-11-02 20:05 UTC, jzuken commented on src/main/java/ftp/ClientMain.java
> +        Client client = new ClientImpl(host, port);
после второй команды клиент заведомо отваливается с ошибкой:

list pom.xml
Found 0 files
list src
Broken pipe

2016-11-02 20:05 UTC, jzuken commented on src/main/java/ftp/ClientMain.java
> +                    case "list":
например, сделать toString() у QueryType

2016-11-02 20:05 UTC, jzuken commented on src/main/java/ftp/impl/QueryType.java
> +public class QueryType {
так лучше сделать enum'ом тогда

2016-11-02 20:05 UTC, jzuken commented on src/test/java/ftp/FtpTest.java
> +    public void testListEmpty() throws IOException {
тест на несколько клиентов к одному серверу хочется ещё

2016-11-05 16:15 UTC, jzuken commented
у меня тест не проходит один:

java.lang.AssertionError: list sizes doesn't match 
Expected :4
Actual   :3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at ftp.FtpTest.testList(FtpTest.java:71)

2016-11-05 16:16 UTC, jzuken commented
и хорошо бы добавить какой-нибудь плагин в мавен, чтобы он собирал полные jar'ники со всеми зависимостями. раз уж мы тут консольные утилиты создаём

2016-11-05 16:20 UTC, jzuken commented
Connection established
LIST .
Found 5 files
src true
pom.xml false
.idea true
target true
.git true
GET pom.xml
test/resources/downloads/pom.xml

Process finished with exit code 0

а это так задумано, что он скачал один файл и завершился? и куда он его сохранить должен был, кстати? в той папке, которую я указал как working directory, ничего не появилось

2016-11-05 16:35 UTC, rbbelka commented
Вероятно, тест не проходит из-за того, что не закоммитить пустую папку.. Она локально у меня лежит и учитывается в тесте.. Исправлю.

> и хорошо бы добавить какой-нибудь плагин в мавен, чтобы он собирал полные jar'ники со всеми зависимостями
Ничего не понятно( То есть, хочется jar, который можно запустить. Что значит добавить плагин? Отдельный какой-то найти, который будет собирать по некоторому конфигу? Или это встроенная фича и надо просто ей сказать, как собирать. И как я ей скажу, как собирать, если для меня это магия мавена)))
В задании, кстати, вроде ничего нет про консольные приложения - это требование уже к следующему дз, кажется. Но в любом случае надо разобраться)

2016-11-06 09:31 UTC, jzuken commented
То есть как нет ничего про консольные приложения? "Требуется реализовать сервер, обрабатывающий два запроса. [...] И клиент, позволяющий исполнять указанные запросы." -- если хотите, можете сделать эти приложения графическими, но запускаться и работать то они должны как-то :)

2016-11-06 09:37 UTC, jzuken commented
По поводу jar -- ну так Вы же не будете всю жизнь запускать проект из IDE. И пользователи Ваши тоже не будут это делать, поэтому научиться собирать самодостаточные бинарники вполне полезно. Особенно если Вы магистр уважаемого университета :)

Раз Вы используете для сборки мавен, у него есть целая куча плагинов (один из них, maven-compiler-plugin, Вы уже используете, к слову, для задания версии джавы), и бинарники умеют собирать аж несколько из них. По запросу "maven jar with dependencies" вам гугл целую кучу вариантов предоставит, самый простой, видимо, maven-assembly-plugin. Почитайте какие-нибудь доки про мавен, полезно понимать, как используемая Вами система сборки работает изнутри.

2016-11-06 09:39 UTC, jzuken commented
кстати, когда исправляется какой-то баг, хорошим тоном считается добавить тест, который проверяет, что баг действительно исправлен. регрессионные тесты -- это хорошо и полезно

2016-11-06 09:43 UTC, jzuken commented
если попытаться скачать get'ом папку, оно создаст пустой файл. задание этот случай не специфицирует, но мне кажется, что это не совсем корректное поведение. надо либо ругаться, либо выкачивать папку целиком (что сложнее, понятно). не зря же мы в list выводим, файл оно или нет

2017-02-06 15:16 UTC, rbbelka commented
@jzuken,
> если попытаться скачать get'ом папку, оно создаст пустой файл. на несуществующих файлах оно ровно так же себя ведёт
Исправила, теперь пишет, что такого файла нет.
> хорошо бы добавить какой-нибудь плагин в мавен, чтобы он собирал полные jar'ники со всеми зависимостями.
Сделано

2017-02-11 11:38 UTC, jzuken requested changes

2017-02-11 11:38 UTC, jzuken commented on src/main/java/ftp/client/ClientImpl.java
> +                    throw new RuntimeException("Cannot connect");
я б, конечно, собственное исключение сделал, причём контролируемое. вот если бы вам потребовалось gui к этому клиенту делать, вряд ли аварийное завершение было бы приемлемой реакцией на ошибку соединения

2017-02-11 11:38 UTC, jzuken commented on src/test/java/ftp/FtpTest.java
> +    private static final String DIR1 = "dir1";
давайте тут использовать TemporaryFolder Rule, раз уж мы его проходили

2017-02-11 11:38 UTC, jzuken commented on src/test/java/ftp/FtpTest.java
> +    public void testListEmpty() throws IOException, InterruptedException {
это всё интеграционные тесты, которые проверяют всю работу приложения в целом. а как проверить отдельно логику работы клиента, например? (предположим, что вы разрабатываете только клиент, а сервер программирует кто-то другой).

2017-02-11 11:38 UTC, jzuken commented on src/main/java/ftp/client/ClientMain.java
> +                            String dirPath = scanner.next();
а если просто написать list без аргументов, оно вообще ничего не говорит. а можно было бы вывести корневой каталог или сказать, что нужен аргумент

2017-02-11 11:38 UTC, jzuken commented on src/main/java/ftp/client/ClientMain.java
> + * Main class to run client
ну и javadoc давайте потренируемся писать всё же, а то как-то совсем грустно

2017-02-14 21:32 UTC, rbbelka commented on src/main/java/ftp/client/ClientMain.java
> +                            String dirPath = scanner.next();
Не ничего не говорит, а ждёт, пока не введут хоть какой-то аргумент) и при вводе этого аргумента уже обрабатывает команду.
Но хорошо, исправила.

2017-02-15 10:23 UTC, rbbelka commented on src/main/java/ftp/client/ClientMain.java
> + * Main class to run client
Написала для клиента

2017-02-15 10:25 UTC, rbbelka commented on src/test/java/ftp/FtpTest.java
> +    public void testListEmpty() throws IOException, InterruptedException {
@jzuken пока без модульных тестов, не успеваю.

2017-02-20 22:12 UTC, merged